resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      products:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 4s
    instances:
      products:
        base-config: defecto


spring:
    cloud:
        gateway:
            routes:
            - id: mvs-products
              uri: lb://mvs-products
              predicates:
              - Path=/api/products/**
              # - Header=token, 12345
              # - Header=token, \d+ # expresiones regulares
              # - Method=GET, POST
              # - Query=color, rojo
              # - Cookie=color, azul
              # - Header=Content-Type, application/json
              filters:
              - name: CircuitBreaker
                args:
                  name: products
                  statusCodes: 500
                  fallbackUri: forward:/api/items/5 #url de error
              - StripPrefix=2
              - name: SampleCookie
                # args:
                #   #Si alguno falta no se pasa. Esto viene de los filtros globales (SampleCookie)
                #   message: Hola mi mensaje personalizado para productos
                #   name: user
                #   value: Yael
            - id: mvs-items
              uri: lb://msv-items
              predicates:
              - Path=/api/items/**
              filters:
              - StripPrefix=2
              # Factories que vienen por defecto
              - AddRequestHeader=token-request, abcdefghijk
              - AddResponseHeader=token-response, 121324121
              - AddRequestParameter=name, Yael
              - SetResponseHeader=Content-Type, text/plain